name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_fplforecaster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'fplforecaster' }}
      run: |
        docker login --username=yannikaramanis@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
